var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                 o #                   o                                        ",
   "                   xxx   xxxxxx    x   x                                        ",
   "                                            x                                   ",
   "                                                   x                            ",
   "                                           o                                    ",
   "                                                                                ",
   "x                                o               y                              ",
   "x                                       y          xxxxxxxxxxxx                 ",
   "x                                     *   xxxx                 o  *             ",
   "x           o          *o           xxx                         y xxxx          ",
   "x        *                     xxx                              x       xxxx    ",
   "x @      y           y                                                          ",
   "xxxxxxx    xxxxxxxx    xxxxxx                                                   ",
   "xxxxxxx    xxxxxxxx    xxxxxx                                                   ",
   "xxxxxxx!!!!xxxxxxxx!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxx!!!!xxxxxxxx!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxx!!!!xxxxxxxx!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxx!!!!xxxxxxxx!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
    
    
    
    
    
    
  ["        xx          xx xx   xx     xx   xx     xx  xxxxxxx   xxxxxx              ",
   "         xx        xx       xxxx   xx   xxxx   xx  xx        xx  x               ", 
   "          xx  xx  xx   xx   xx xx  xx   xx xx  xx  xxxxx     xxxx                ", 
   "           xx xx xx    xx   xx  xx xx   xx  xx xx  xx        xx  xx              ",
   "            xx  xx     xx   xx   xxxx   xx   xxxx  xxxxxxx   xx   xx             ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "      @                                                       o                  ", 
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ",
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 "], 
   
   
   
  ["                                                                                 ", 
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                          x                                      ",
   "                                          x    x                                 ",
   "                                          x    x                                 ",
   "                                          x    x                                 ",
   "                                          xo   x                             o   ",
   "                                          xx   xxxxxxxxxxxxxxxxxxxx    yy    y   ",
   "x                                         x    x                                 ",
   "x                                         x   #x                                 ",
   "x           o        o                    x   xx                                 ",
   "x       xxxxx     xxxx                    x    x                                 ",
   "x  @                                      x                                      ",
   "x xxx                                    oxxx                                    ",
   "x                           xxxxxxxxxxxxxxx   oxxxxxxxxxxxx                      ",
   "x     xxxx                                    x                                  ",
   "x                                                                                ",
   "x                                                                                ",
   "x                                                                                ",
   "x          xxx                                              o                    ",
   "x                                                          xx                    ",
   "x                                                                                ",
   "x              xxx                               o  xxxxxx                       ",
   "x                     o          o     o        xx                               ",
   "x                     yy    yy   yy    y     yy                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
      
   ["       xx          xx xx   xx     xx   xx     xx  xxxxxxx   xxxxxx              ",
   "         xx        xx       xxxx   xx   xxxx   xx  xx        xx  x               ", 
   "          xx  xx  xx   xx   xx xx  xx   xx xx  xx  xxxxx     xxxx                ", 
   "           xx xx xx    xx   xx  xx xx   xx  xx xx  xx        xx  xx              ",
   "            xx  xx     xx   xx   xxxx   xx   xxxx  xxxxxxx   xx   xx             ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "      @                                                       o                  ", 
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ",
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 "],  
      
      
  ["                                                                                                                  ",
   "   @       o        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    ",
   "xxxxxxxxxxxx       !!xxvvxxxxxxvvxxvvxxxxxxxxxxxxxxxxxxvvxxxxxxxvvxxxxxxxxxvvxxxxxxvvxxxxxxxvvxxxxxxxxxvvxxxxx    ",
   "           x       vvxxvvxxxxxxvvxxvvxxxxxxxxxxxxxxxxxxvvxxxxxxxvvxxxxxxxxxvvxxxxxxvvxxxxxxxvvxxxxxxxxxvvxxxxx    ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x       vv                                                                                             ",
   "           x    yy vv                        x                                                                   o",
   "           x       vv                    o       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxx",
   "           x       vv                   yy                                                       x        x       ",
   "           x       vv                                                                            x        x       ",
   "           x       vv                                                                            x        x       ",
   "           x       vv           !!!!!x                                                           x        x       ",
   "           x       vv           xxxx!!                           xxxxxxxxxxxxxx                  x        x       ",
   "           x       vv               vv  x                       x              x                 x        x       ",
   "           x       vv                            xxxxxxxxxxxxxxxx              xxxxxxx           x        x       ",
   "           x       vv                      xx                                                    x        x       ",
   "           x       vv                                                                    o       x        x       ",
   "           x       vv                                                                    x       x        x       ",
   "           x       vv                                       o       o                            x        x       ",
   "           x       vv                                                      o        xxxx         x        x       ",
   "           x       vv                                       x   y  yy    yy    yy                x        x       ",
   "           x       vv                           !!!!   o        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   x        x       ",
   "           x       vv                           xxxx!! x        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   x        x       ",
   "           x       vv                                           xxxxxxxxxxxxxxxxxxxxxxxxvvxxxx   x        x       ",
   "           x       vv                                                                            x        x       ",
   "           x       vv                                     xxx                                    x        x       ",
   "           x       vv                                                                            x        x       ",
   "           x       vv                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x        x       ",
   "           x       vv                                          !!!!!!!!!!!!!!!!!!!!!!!!!v        x        x       ",
   "           x       vv                                          xxxvvxxxxvvxxxxxxvvxxxxvv       o xxxxxxx  x       ",
   "           x       vv                                                                         xxxx     x  x        ",
   "           x                                                                                           x  x        ",
   "           x                                                                                           x  x        ",
   "           x                                                                                           x  x        ",
   "           x                             o                            o       o                        x  xxxxxxxx ",
   "           x                          xxxx       *       o     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x        #x ",
   "           x                                    xxxxxxxxxx                                             xxxxxxxxxxx ",
   "           xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "],
    
    
  ["        xx          xx xx   xx     xx   xx     xx  xxxxxxx   xxxxxx              ",
   "         xx        xx       xxxx   xx   xxxx   xx  xx        xx  x               ", 
   "          xx  xx  xx   xx   xx xx  xx   xx xx  xx  xxxxx     xxxx                ", 
   "           xx xx xx    xx   xx  xx xx   xx  xx xx  xx        xx  xx              ",
   "            xx  xx     xx   xx   xxxx   xx   xxxx  xxxxxxx   xx   xx             ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "      @                                                                          ", 
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 ",
   "                                                                                 ", 
   "                                                                                 ", 
   "                                                                                 "],    
    
  
  
    
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;